name = "nbafinals"
compatibility_date = "2023-12-01"

[durable_objects]
bindings = [{ name = "OPTION1", class_name = "Option1" }, { name = "OPTION2", class_name = "Option2"}]

[[migrations]]
tag = "v1"
new_classes = ["Option1", "Option2"]

[ai]
binding = "AI"